// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func ContentView() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section id=\"content-view\" class=\"page min-h-screen hidden\"><div class=\"fade-in\"><button id=\"back-btn\" class=\"mb-8 inline-flex items-center gap-2 text-[9px] text-[#555555] border border-[#2a2a2a] px-3 py-2 uppercase tracking-widest hover:border-[#4ade80] hover:text-[#4ade80] transition-colors\" style=\"font-family:var(--font-pixel);\">&larr; Back</button><div class=\"border border-[#2a2a2a] bg-[#0f0f0f]\"><!-- Terminal titlebar --><div class=\"flex items-center gap-2 px-4 py-2 border-b border-[#2a2a2a] bg-[#0a0a0a]\"><div class=\"w-2.5 h-2.5 rounded-full bg-[#e05555]\"></div><div class=\"w-2.5 h-2.5 rounded-full bg-[#d4905a]\"></div><div class=\"w-2.5 h-2.5 rounded-full bg-[#4ade80]\"></div><span class=\"ml-3 text-[#555555] text-[12px]\" style=\"font-family:var(--font-term);\">transmission.log</span></div><div id=\"dynamic-content\" class=\"prose max-w-none\"></div></div></div></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
