// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func ContentView() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section id=\"content-view\" class=\"page min-h-screen hidden\"><div class=\"fade-in\"><button id=\"back-btn\" class=\"mb-8 inline-flex items-center gap-2 text-[10px] text-[#18130e] bg-[#e8e2d4] border-[2px] border-[#18130e] px-3 py-2 uppercase tracking-widest hover:bg-[#c42a1c] hover:text-[#f0ebe0] hover:border-[#c42a1c] transition-colors shadow-[2px_2px_0px_rgba(24,19,14,0.2)]\" style=\"font-family: var(--font-pixel);\"><span>&larr;</span> BACK TO DISPATCHES</button><div class=\"bg-[#f0ebe0] border-[3px] border-[#18130e] shadow-[8px_8px_0px_#18130e] relative\"><div class=\"absolute top-[-10px] left-1/2 -translate-x-1/2 w-[120px] h-[24px] bg-[rgba(240,192,0,0.55)] rotate-[2deg] shadow-[0_1px_3px_rgba(0,0,0,0.12)] z-10 pointer-events-none\"></div><div id=\"dynamic-content\" class=\"prose max-w-none\"></div></div></div></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
