// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/conjon1/rebooterzine/model"
import "github.com/conjon1/rebooterzine/assets"

func HomeSection(posts []model.Post) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section id=\"home\" class=\"page min-h-[80vh]\"><div class=\"fade-in border-b border-[#2a2a2a] pb-12 mb-12\"><div><pre class=\"text-[#4ade80] text-[18px] sm:text-[20px] leading-[1.15] mb-8 select-none overflow-x-auto\" style=\"font-family:var(--font-term);\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ.Raw(assets.GetASCII("rebooter.txt")).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</pre><div class=\"text-[18px] text-[#888888] mb-8\" style=\"font-family:var(--font-term);\"><span class=\"text-[#e05555]\">root@reboot:~#</span> <span id=\"typewriter\"></span><span class=\"cursor\"></span></div><div class=\"border border-[#2a2a2a] bg-[#0f0f0f] p-5 relative\"><div class=\"absolute -top-[11px] left-4 bg-[#0a0a0a] px-2 text-[#555555] text-[11px]\" style=\"font-family:var(--font-body);\">/var/log/system.log</div><div class=\"text-[14px] text-[#888888] leading-[1.9]\" style=\"font-family:var(--font-body);\"><p class=\"mb-1\"><span class=\"text-[#e05555]\">[ERR]</span> Dark Crystals of Programming stolen.</p><p class=\"mb-1\"><span class=\"text-[#d4905a]\">[WARN]</span> Corquettes constructing super weapon.</p><p class=\"mb-3\"><span class=\"text-[#5ec4d4]\">[INFO]</span> Target: hypermories (caffeine guardians).</p><p class=\"mb-1\"><span class=\"text-[#4ade80]\">[EXEC]</span> Gathering unix wizards...</p><p class=\"text-[#c8c8c8]\">&gt; Mission: fight back. Reboot the system.</p><p class=\"mt-3 text-[#555555]\">-- Signed: Kesh --</p></div></div></div></div><div class=\"fade-in\"><div class=\"flex items-center gap-4 mb-8\"><span class=\"text-[18px] text-[#555555]\" style=\"font-family:var(--font-term);\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs("// recent dispatches")
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/home.templ`, Line: 36, Col: 106}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</span><div class=\"flex-1 border-t border-[#2a2a2a]\"></div></div><div class=\"grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if len(posts) == 0 {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<p class=\"text-[#555555]\" style=\"font-family:var(--font-term);\">No posts found.</p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			for _, post := range GetRecent(posts, 3) {
				templ_7745c5c3_Err = PostItem(post).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</div><a href=\"#blog\" class=\"nav-link inline-block mt-8 text-[14px] text-[#555555] hover:text-[#4ade80] transition-colors\" style=\"font-family:var(--font-term);\">&gt; view all transmissions _</a></div></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
