// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/conjon1/rebooterzine/model"

func HomeSection(posts []model.Post) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section id=\"home\" class=\"page min-h-screen\"><div class=\"fade-in\"><h1 class=\"text-4xl md:text-6xl font-bold mb-4 text-[#61afef]\">Rebooter</h1><h2 class=\"text-2xl md:text-3xl text-[#c678dd] mb-8\"><span id=\"typewriter\"></span><span class=\"cursor\"></span></h2><p class=\"max-w-3xl text-lg leading-relaxed mb-16\">Runtime error: Programming not found. \"The Dark Crystals of Programming\" have been stolen by the Corquettes and are being used to construct a super weapon that will be used against the hypermories, the guardians who defend against a complete caffeine drought for programmers. In order to save the world and the future of programming, an eagle from the transcendental realm that hosts the soul of Alexander the Great, under the orders of a mysterious ancient figure, gathered various unix wizards from the early 21st Century to fight back against the Corquettes and reboot the system. - Kesh</p></div><div class=\"fade-in mt-12\"><h3 class=\"text-3xl font-bold mb-8 border-b-2 border-[#61afef] pb-2\">Recent Posts</h3><div class=\"space-y-6\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if len(posts) == 0 {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<p class=\"text-[#5c6370]\">No posts found.</p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			for _, post := range GetRecent(posts, 3) {
				templ_7745c5c3_Err = PostItem(post).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div><a href=\"#blog\" class=\"nav-link inline-block mt-8 text-[#c678dd] hover:text-[#61afef] transition-transform hover:translate-x-1\">View all posts &rarr;</a></div></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
