// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Nav() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<header class=\"sticky top-0 z-[200] border-b border-[#2a2a2a] bg-[#0a0a0a]\"><div class=\"grid grid-cols-[auto_1fr_auto] items-stretch\"><div class=\"px-6 py-3 border-r border-[#2a2a2a] flex flex-col justify-center\"><a href=\"#home\" class=\"text-[#4ade80] text-2xl leading-none tracking-widest hover:text-white transition-colors\" style=\"font-family:var(--font-term);\">&gt; REBOOTER_</a><div class=\"mt-1 text-[#555555] text-[10px]\" style=\"font-family:var(--font-body);\">[ INIT ] <span id=\"nav-spinner\" class=\"text-[#4ade80] ml-1\">[-]</span></div></div><div class=\"hidden md:flex items-center px-8 gap-8\"><a href=\"#home\" class=\"text-[#888888] hover:text-[#c8c8c8] text-[16px] tracking-widest transition-colors\" style=\"font-family:var(--font-term);\">&gt; Home</a> <a href=\"#blog\" class=\"text-[#888888] hover:text-[#c8c8c8] text-[16px] tracking-widest transition-colors\" style=\"font-family:var(--font-term);\">&gt; Dispatches</a> <a href=\"#authors\" class=\"text-[#888888] hover:text-[#c8c8c8] text-[16px] tracking-widest transition-colors\" style=\"font-family:var(--font-term);\">&gt; Authors</a></div><div class=\"hidden md:flex flex-col justify-center px-6 border-l border-[#2a2a2a]\"><div class=\"text-[#4ade80] text-[11px]\" style=\"font-family:var(--font-term);\">TTY1</div><div class=\"text-[#555555] text-[10px] mt-0.5\" style=\"font-family:var(--font-body);\">UPTIME: 99.9%</div></div></div></header>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
