// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Nav() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<header class=\"bg-[#282c34]/80 backdrop-blur-md sticky top-0 z-50 border-b border-[#5c6370]\"><div class=\"container mx-auto px-6 py-4 flex justify-between items-center\"><a href=\"#home\" class=\"text-xl font-bold font-mono text-[#61afef]\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs("// Rebooter")
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/nav.templ`, Line: 6, Col: 85}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</a><nav class=\"hidden md:flex space-x-8 items-center\"><a href=\"#home\" class=\"nav-link hover:text-[#61afef] transition-colors\">Home</a> <a href=\"#blog\" class=\"nav-link hover:text-[#61afef] transition-colors\">Blog</a> <a href=\"#authors\" class=\"nav-link hover:text-[#61afef] transition-colors\">Authors</a></nav><button id=\"mobile-menu-btn\" class=\"md:hidden text-[#abb2bf] hover:text-[#61afef] focus:outline-none\"><svg xmlns=\"http://www.w3.org/2000/svg\" class=\"h-8 w-8\" fill=\"none\" viewBox=\"0 0 24 24\" stroke=\"currentColor\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M4 6h16M4 12h16m-7 6h7\"></path></svg></button></div><div id=\"mobile-menu\" class=\"hidden md:hidden bg-[#282c34] border-b border-[#5c6370]\"><nav class=\"flex flex-col px-6 py-4 space-y-4\"><a href=\"#home\" class=\"mobile-link hover:text-[#61afef] transition-colors\">Home</a> <a href=\"#blog\" class=\"mobile-link hover:text-[#61afef] transition-colors\">Blog</a> <a href=\"#authors\" class=\"mobile-link hover:text-[#61afef] transition-colors\">Authors</a></nav></div></header>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
