// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Ticker() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"flex h-[34px] w-full overflow-hidden border-b-[3px] border-[#18130e] bg-[#c42a1c]\"><div class=\"flex shrink-0 items-center border-r-[3px] border-[#9a1e12] bg-[#18130e] px-4 text-[7px] text-[#f0ebe0]\" style=\"font-family: var(--font-body);\"></div><div class=\"flex flex-1 items-center overflow-hidden whitespace-nowrap\"><div class=\"ticker-scroll flex whitespace-nowrap\"><span class=\"px-8 text-[11px] tracking-[0.08em] text-[#f0ebe0] before:mr-2 before:text-[8px] before:opacity-60 before:content-['✦']\" style=\"font-family: var(--font-body);\">HYPERMORIES</span> <span class=\"px-8 text-[11px] tracking-[0.08em] text-[#f0ebe0] before:mr-2 before:text-[8px] before:opacity-60 before:content-['✦']\" style=\"font-family: var(--font-body);\">CORQUETTES</span> <span class=\"px-8 text-[11px] tracking-[0.08em] text-[#f0ebe0] before:mr-2 before:text-[8px] before:opacity-60 before:content-['✦']\" style=\"font-family: var(--font-body);\">DARK CRYSTALS</span> <span class=\"px-8 text-[11px] tracking-[0.08em] text-[#f0ebe0] before:mr-2 before:text-[8px] before:opacity-60 before:content-['✦']\" style=\"font-family: var(--font-body);\">TRANSCENDENTAL EAGLE</span> <span class=\"px-8 text-[11px] tracking-[0.08em] text-[#f0ebe0] before:mr-2 before:text-[8px] before:opacity-60 before:content-['✦']\" style=\"font-family: var(--font-body);\">HYPERMORIES</span> <span class=\"px-8 text-[11px] tracking-[0.08em] text-[#f0ebe0] before:mr-2 before:text-[8px] before:opacity-60 before:content-['✦']\" style=\"font-family: var(--font-body);\">CORQUETTES</span></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
