// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package posts

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/conjon1/rebooterzine/components"
	"github.com/conjon1/rebooterzine/model"
)

func init() {
	Register(model.Post{
		ID:       "CertCIndustries",
		Title:    "Industries in Demand for CERT C Compliant Security-Focused Coders",
		Date:     "November 22, 2025",
		Author:   "Tanveer Salim",
		AuthorID: "tanveersalim",
		Excerpt:  "The Therac-25 disaster taught us that bugs in C code can be lethal. Learn why aerospace, automotive, and medical industries now mandate CERT C compliance to prevent vulnerabilities in life-critical systems.",
	}, CertCIndustries)
}

func CertCIndustries(post model.Post) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<p>Between 1985 and 1987, a radiation therapy machine called the Therac-25 killed three people and seriously injured three others. The machine was supposed to deliver controlled doses of radiation to cancer patients. Instead, it delivered radiation doses hundreds of times higher than intended.</p><p>The cause? A race condition in the C code controlling the machine. Whenever an operator entered treatment parameters too quickly, the software would configure the machine for high-energy electron mode while the safety mechanisms thought it was in low-energy X-ray mode.</p><p>The Therac-25 disaster wasn&apos;t caused by sophisticated hackers or nation-state attackers. It was caused by a simple bug—the kind of concurrency error that CERT C rules are specifically designed to prevent. This is what happens when C code controlling life-critical systems has bugs. People die.</p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.SectionHeader("Aerospace: Where Every Line of Code Gets Audited").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, " <p>Flight control software runs on embedded systems with no room for error. You&apos;re at 35,000 feet when the autopilot makes a calculation. That calculation depends on sensor data stored in memory. If a buffer overflow corrupts the memory location next to that sensor data, the autopilot is now making decisions based on garbage values.</p><p>The <code>gets()</code> function in C will copy characters into a buffer regardless of the buffer&apos;s size. Aerospace companies mandate CERT C compliance because they&apos;ve debugged these exact bugs in code that was controlling actual aircraft. When aerospace engineers read CERT C Rule ARR30-C—\"Do not form or use out-of-bounds pointers or array subscripts\"—they&apos;re not reading a style guideline. They&apos;re reading a rule written in blood.</p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.SectionHeader("Automotive: Your Car is a Computer on Wheels").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, " <p>I want you to imagine something. You&apos;re driving on the highway. Your adaptive cruise control maintains distance from the car ahead. The distance sensor returns a measurement. The code multiplies this measurement by a constant to calculate braking force. What happens when that multiplication overflows?</p><p>In C, when you multiply two integers and the result exceeds the maximum value the integer type can hold, you don&apos;t get an error. You get wraparound. A large positive number becomes small. Or negative, if you&apos;re unlucky. Your car&apos;s computer thinks the vehicle ahead is either impossibly close or impossibly far away.</p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.SectionHeader("Medical Devices: Code Running Inside Your Body").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, " <p>If automotive software is dangerous when it fails, medical device software is even worse. Because when medical device code has bugs, there&apos;s no recall notice. There&apos;s no software update. The code is running inside someone&apos;s body.</p><p>A pacemaker is a small computer implanted in your chest. Now imagine the code has a null pointer dereference. In a desktop application, you&apos;d get a segmentation fault, the program would crash, and you&apos;d restart it. In a pacemaker implanted in someone&apos;s chest, the device crashes and stops monitoring heart rhythm.</p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.SectionHeader("IoT Devices: Billions of Targets").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, " <p>Smart locks on apartment doors. Baby monitors in bedrooms. Industrial sensors in manufacturing plants. Most run embedded C code on processors with no memory protection, no operating system security features, no runtime bounds checking. Take a look at a simple example:</p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.CodeBlock("c", `char buffer[64];
gets(buffer);  // Read the setpoint command`).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, " <p>The <code>gets()</code> function copies input into the buffer regardless of size. An attacker sends 200 bytes. Your 64-byte buffer overflows. Adjacent memory gets corrupted. Multiply this by millions of IoT devices all making the same mistake, and you have a massive botnet capable of taking down internet infrastructure.</p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.Callout("info", "82% of software vulnerabilities come from coding errors. Not zero-days. Not sophisticated exploits. Just bugs in the code.").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = components.PostLayout(post).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
