// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package posts

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/conjon1/rebooterzine/components"
	"github.com/conjon1/rebooterzine/model"
)

func init() {
	Register(model.Post{
		ID:       "K3S",
		Title:    "My Homelab Journey: From Mini PCs to Kubernetes with K3s",
		Date:     "October 20, 2025",
		Author:   "Connal McInnis",
		AuthorID: "connalmcinnis",
		Excerpt:  "From a few mini PCs to a fully functional Kubernetes cluster – my homelab journey using Ubuntu and K3s has been full of learning experiences.",
	}, K3s)
}

func K3s(post model.Post) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<p><strong>From a few mini PCs to a fully functional Kubernetes cluster – my homelab journey using Ubuntu and K3s has been full of learning experiences (and a few headaches!).</strong></p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.SectionHeader("Motivation: The Pull of Automation").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, " <p>I&apos;ve always been drawn to automation and building effective, interconnected systems. This interest was likely first sparked by games like Minecraft with its automatic farms, and later solidified by titles like Factorio and Mindustry. In Factorio, in particular, you design intricate, interconnected factories to automate production towards launching a rocket – it&apos;s incredible dopamine, like candy for my brain. This love for building complex systems naturally led me to explore the world of container orchestration with Kubernetes.</p><h3>Why K3s?</h3><p>When I discovered K3s, I was immediately interested. It seemed like a great starting point: providing a solid Kubernetes foundation that was relatively easy to set up but didn&apos;t abstract away too much, unlike options like MicroK8s from Canonical.</p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.SectionHeader("The Hardware").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, " <p>For my Kubernetes homelab, I chose 3x Beelink EQ12 mini PCs. These compact machines offered the perfect blend of low power consumption and sufficient processing power.</p><ul><li><strong>Processor:</strong> Each unit features an efficient Intel processor.</li><li><strong>RAM:</strong> 24GB DDR5 RAM per unit.</li><li><strong>Storage:</strong> 500GB NVMe SSD per unit.</li></ul><p>Across the three nodes, this gives a total of 30 cores and 36 threads, which is a decent amount of processing power for this learning project.</p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.SectionHeader("The Operating System: Ubuntu with a Security Twist").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, " <p>Initially, I tried running Talos Linux, but I quickly realized I was a bit out of my depth. Getting the system configured exactly as I wanted proved challenging (mostly user error, honestly!). I also considered Arch Linux, but having used it as my primary desktop OS for years, I anticipated potential maintenance headaches down the line.</p><p>So, I turned my attention to Debian-based systems, and Ubuntu immediately came to mind. For added security, I opted for LUKS full-disk encryption on each node.</p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.SectionHeader("Getting Hands-On: Installing K3s on Ubuntu").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, " <p>With the hardware chosen and Ubuntu Server 24.04.2 LTS installed on my three \"honey\" nodes, it was time to dive into the K3s installation.</p><h3>Disabling the Firewall</h3>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.CodeBlock("bash", `sudo ufw disable
sudo systemctl disable ufw`).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, " <h3>Installing the K3s Control Plane (on honey1)</h3>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.CodeBlock("bash", `curl -sfL https://get.k3s.io | sh -
sudo cat /etc/rancher/k3s/k3s.yaml`).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, " <h3>Joining the Worker Nodes (honey2 & honey3)</h3>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.CodeBlock("bash", `curl -sfL https://get.k3s.io | K3S_URL=https://<honey1-ip>:6443 K3S_TOKEN=<your-token> sh -`).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, " ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.SectionHeader("Monitoring with Prometheus & Grafana").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, " <p>With the cluster running, the next step was setting up a monitoring stack using Prometheus and Grafana via a Helm chart.</p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.CodeBlock("bash", `helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
helm repo update

helm install prometheus-stack prometheus-community/kube-prometheus-stack \
  --namespace=prometheus-stack \
  --create-namespace`).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, " <h3>Making Access Easier: NodePort and Ingress</h3>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.CodeBlock("yaml", `# grafana-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: prometheus-stack
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: grafana
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30001`).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, " ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.Callout("tip", "After applying the ingress route, you can easily access the dashboard at grafana.local.").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = components.PostLayout(post).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
